#+TITLE: Mothica @ Pub Station — Spin The Wheel Tour
#+OPTIONS: toc:nil num:nil
#+DATE: 2026-03-28

I went to a Mothica concert on 3/28/2026! The lineup was Diamante, Until I Wake, Mothica, then I See Stars. It was such an amazing time.

* The Moth Resume

Before I headed to Billings, I was taking a shower and thought, "You know what would be fun? Making a resume for a moth since Mothica is in her 'Mothicorp' era." So instead of driving to Billings at noon like I originally had planned, I spent an hour and a half drawing a suit on a moth I found online and researching what moths would say when applying for a job.

[link psd here]
[link picture of the resume here]

Once I finished, I called up Wadhams who lives across the street to see if I could use his printer. It was good timing since he was about to go on a camping trip with Clara. I print two copies, then head to Billings a little before 2pm.

* Arriving at the Venue

I check into my Dude Rancher Lodge hotel room (weird name but the place had a fun Western personality to it without being cringey), and called Tony on the phone. Mothica said she sometimes goes to the merch table right after her show to say hi to fans — the main reason I made the moth resume — but she posted a story on her Instagram saying she needed to rest her voice instead. Totally understandable; the Spin The Wheel tour was BRUTAL. Despite that, I figured I'd bring one of my resume copies.

This was my first time going to a concert alone so I figured I'd just show up once the doors opened at 7 instead of getting there early to be the first to enter like I typically did in the past. There was a very short line. I get to the Pub Station and first thing I do is check out the merch tables, which were directly in front of the doors as you entered the venue. There was only a couple people in front of me so I internally argued what I should and shouldn't buy.

Once it was my turn, I told the nice merch lady, "Hello, may I please get I'd like a large sweatshirt— oh my god is that a drum head?" The other customers had blocked my view of it, but there was this lightly used drumhead with a big moth drawing with stars floating around it. It had the date, and two signatures: Mothica's and the drummer she's touring with, Carter Vaughan. It was only $100... Obviously I had to get it.

[insert picture of drum head here]

The merch lady said it was the only one. They aren't guaranteed at every show and she'll only draw on one if they can spare it and if she's feeling it. As she was ringing my order up, we had a little conversation about the tour and I asked if she was a fan — she gave me a smile and said yes! There was nobody in line after me so I wasn't holding anyone up, so I figured she would get a laugh out of the moth resume I made. I pull the folded up piece of paper out of my pocket and hand it to her. She laughed at it and offered to give it to Mothica! I wasn't expecting that at all, but I said that'd be super nice of her! I officially felt accomplished at this concert. I put on the sweatshirt and carried the drumhead around.

* Diamante

It wasn't soon after until Diamante started her set. I sat in the semi-back right of the showroom for her and Until I Wake. I listened to a couple of her songs when I first heard about this tour — /1987/ being the only one I remembered — and I enjoyed her sound on Spotify as a whole but hadn't given her enough time to become a consistent listen (same with the other bands). The crowd was a little weak with her, as most openers suffer from, but her vocals were very impressive. She can definitely belt. The guitarists were rocking some awesome solos too. I enjoyed her show and I was trying to be interactive by throwing my empty hand up for most of it.

After her set she went to her merch stand to take photos and say hi. There was a long line and I got in it for a second, but Until I Wake started playing and the line didn't move very fast — I'd rather see the start of the next set.

[Diamante videos here]

* Until I Wake

Until I Wake is more of a half-screamo band. SUPER GOOD! You can tell that most of the artists' voices were strained (again, BRUTAL tour) but the lead singer had his screams on point. I need to check them out more. Their tour bus driver got sick so the band members had to take shifts driving the bus. They also went to their merch stand after, but I needed to see Mothica.

They had pit form a few times during their songs, and a big one to end their set. This was the perfect time to sneak from the back to the front. I was basically second row, with one person truly in front of me and I could see over her head no problem. Perfect view, basically front row.

* Mothica

As the time comes, she starts /Toxic/. Her touring guitarist Alex tells us that he had the best burger of his life at the Burger Dive (huge compliment since he's probably had burgers in every state), and they played a great set. She also had a strained voice but was giving the crowd a great show. She did a really cool half-slowed/half-faster version of /Forever Fifteen/ after giving a speech about how she tried to end her life — that was a teary-eyed moment for me.

She plays another song, and then something I never expected happened: she says this has never happened before, then *PULLS OUT THE RESUME I QUICKLY MADE ON STAGE!!!* I was so hyped. After explaining to the crowd what Mothicorp is, she read the name, said that he was a night shift pollination specialist, and read the part about him being a top Mothica fan with one of his favorite songs being /TEARS/, and how he circles porchlights as a hobby. She loved it, I was so happy.

I was in the front row so I yelled, "That's mine!!!" Mothica looks through the crowd after hearing that, points me out, looks me in the eye and says, "You made this?" I start nodding my head and I hold up the drumhead she drew earlier to show I'm a big fan.

*Life. Fulfilled. Amazing. Astonishing.*

I can't believe she pointed me out to the crowd because of some silly idea I had an hour and a half before I was supposed to drive over to Billings. One of the photographers behind the barrier gestured me to hold the drum head up again, and the concert continued. This was so much better than I could have expected. I was originally a little bummed since she wasn't going to go to her merch stand after playing, but I got an autograph (way cooler than on a CD), Mothica got to see the resume I made (and I realized a couple mistakes in it after — this will haunt me forever), AND SHE INTERACTED WITH ME!! Best possible outcome.

The rest of the concert was amazing. I was jumping up and down screaming the lyrics to all her songs. I saw on the setlist that she's played an unreleased song called /PLAYING-GOD/ on other tour stops, but unfortunately she didn't play it today. Last couple of songs were /VICES/ and /Casualty/. Amazing. 10/10. Would go again.

* I See Stars

After her set, I leave the front row to make room for bigger I See Stars fans and grab a beer (Goose IPA). One guy came up to me and said congrats and we had a brief conversation, then a couple guys in front of us overheard and turned around. One of the guys walks away. The guy I met was named Robert — born and raised in Billings, here because he works at the Pub Station and likes to see shows (doesn't get in for free though). He called himself a poser, and I was like "nah, you're just expanding your music taste." We laughed about it. He told me how he started working in the kitchen there and took some shifts covering for people at the merch stand. He said the metal shows are people cosplaying as mean people, while the pop-ier fans are mean people cosplaying as nice people, haha. We had a good laugh and went on our way.

I See Stars finally came on — one of their first songs was /New Demons/, which is the only song I know. I stayed to the back left of the venue. I was tired from Mothica's set but I stayed for their whole set, and it was super good. The crowd was electric. They said they don't do encores to end... but Billings refused. We got a one-of-a-kind show: the only concert on that leg of the tour (at least before 3/26) that got an encore. Amazing show.

[videos here probably]

* Aftermath

I checked Instagram and saw that Mothica posted my resume on her story!

[screenshot here]

I commented and said that was me, shouted out the merch lady who made this all happen, then thanked her for the amazing show and for coming out to Montana. I finally got to tell her that her music has helped me more than she'll ever know. Surprisingly, she responded very quickly in all caps: "AWWWW THANKS YOU MADE MY NIGHT!!!$". That made my week.

[screenshot here]

Next day, Mothica posted my resume on her official Instagram — so Frederick Lampington will live on forever.
